#!/bin/sh

self="$(realpath "$0")"
home="$(dirname "$self" | xargs -d '\n' dirname | xargs -d '\n' dirname)"
user="$(basename "$home")"

export USER="$user"
export HOME="$home"
export DISPLAY=:0.0
export XAUTHORITY="/run/user/$(id -u "$user")/lyxauth"
export XDG_CONFIG_HOME="$HOME/.config"

# echo "$self" "$HOME" "$USER" "$DISPLAY" "$XAUTHORITY" "$XDG_CONFIG_HOME"
# exit
