# music_directory    "/home/kendfss/Music/library"
music_directory    "/mnt/elements/nicotine/downloads"
playlist_directory "/home/kendfss/.config/mpd/playlists"
db_file            "/home/kendfss/.config/mpd/database"
sticker_file       "/home/kendfss/.config/mpd/sticker"
log_file           "/tmp/mpd/log"
pid_file           "/tmp/mpd/pid"
# state_file         "/home/kendfss/.config/mpd/state"

# Audio output (using ALSA - common on Void)
audio_output {
    type        "alsa"
    name        "My ALSA Device"
    device      "default"
	enabled     "no"
}
audio_output {
    type    "pipewire"
    name    "PipeWire Output"
	enabled "no"
}
audio_output {
    type    "pulse"
    name    "PulseAudio Output"
	enabled "yes"
}

# Network settings - bind to localhost only
bind_to_address "127.0.0.1"
port            "6600"

auto_update             "yes"
follow_outside_symlinks "yes"
follow_inside_symlinks  "yes"


# Volume control
volume_normalization "no"
mixer_type           "software"
# mixer_control        "Master"
restore_paused       "yes"

audio_buffer_size  "4096"
# buffer_before_play "10%"

input_cache {
    size "512 MB"
}

max_connections "6"

