#!/bin/env zsh

## git add, commit, and push in one tiny interface

set -euo pipefail

fail() {
	[ $# = 0 ] && echo "failed" && exit 1
	echo "failed: $?" && exit 1
}

case $1 in
	'-')
		{ add && commit "$(p)" && push && exit; } || fail
		;;
	'first')
		{ add -hv && commit first\; && gh repo create -s. --private --push -d "$(awk 'NR>=3 && !NF {exit} NR>=3 {gsub(/[][]/, ""); gsub(/\]\[[^]]*\]/, ""); printf "%s%s", $0, (NF ? " " : "")} END {print ""}' README.md)" && exit; } || fail
		;;
esac

if [[ -z $1 ]]; then
	argv[1]=\.
fi
if [[ -z $2 ]]; then
	argv[2]=sorry
fi
if [[ -z $3 ]]; then
	argv[3]=origin
fi
add $1 && commit $2 && push $3
