#!/bin/env zsh

local percentage
if [ -x "$(command -v termux-battery-status)" ]; then
	percentage="$(termux-battery-status | jq .percentage | rg '\d+')"
else
	percentage="$(cat /sys/class/power_supply/BAT0/capacity)"
fi

[ -n percentage ] && printf "%d%%" "$percentage"

