#!/bin/env zsh

if [ -n "$(command -v xclip)" ]; then
	xclip -i -selection clipboard
elif [ -n "$(command -v termux-clipboard-set)" ]; then
	termux-clipboard-set
else
	echo no clipboard setter found
	exit 1
fi
exit $?
