#!/bin/sh
fn() {
  local word
  local echo
  if [ ! -z "$1" ]; then
    word="$1"
    echo=true
  else
    word="$(xclip -o -selection primary 2> /dev/null || xclip -o -selection clipboard || exit)"
  fi
  query="https://api.dictionaryapi.dev/api/v2/entries/en_US/$word"
  result="$(curl -s "$query")"
  if [ -z "$result" ]; then 
    local msg="Invalid word: $word"
    [ -z $echo ] && notify-send -h string:bgcolor:#bf616a -t 3000 "$msg" && return
    echo "$msg" && return
  fi
  local pipeline='[.[].meanings[] | {pos: .partOfSpeech, def: .definitions[].definition}] | .[:3].[] | "\(.pos). \(.def)\n"'
  local def="$(echo "$result" | jq -r "$pipeline" 2> /dev/null || echo "$result" | jq -r '.message' 2> /dev/null || exit)"
  # local def="${def// \\n}"
  [ -z $echo ] && notify-send -t 60000 "$word -" "$def" && return
  echo "$def"
}

fn "$@"



