#!/bin/env zsh

# search github repos, check them each out, and print your choices

set -euo pipefail

local _testing=false
[ $_testing = true ] && set -x

local self=$(basename "$ZSH_ARGZERO")
helpText() {
	cat <<-EOF
		usage: $self [QUERY TERM]...
		     a script for peeking at github repo READMEs

		     query terms will be concatenated into a single query
	EOF
}

local args=()
while (($#)); do
	case "$1" in
		-h | --help)
			helpText
			exit 0
			;;
		-*)
			echo "unrecognized flag: $1" >&2
			helpText >&2
			exit 1
			;;
		*)
			args+="$1"
			shift
			;;
	esac
done

if rg -o '^(code|commits|issues|prs|repos)$' <(echo "${args[1]}") &>/dev/null; then
	mode="${args[1]}"
	shift args
else
	mode="repos"
fi

tmp="$(mktemp -d)"
rm -rf "$tmp"
DIR="$(dirname "$tmp")/$(basename "$ZSH_ARGZERO")"
[ "$mode" = "repos" -o "$mode" = "prs" -o "$mode" = issues ] && DIR="$DIR/$mode"

[ $_testing = true ] && echo "$DIR"
[ ! -e "$DIR" ] && mkdir -p "$DIR"

viewer="$(command -v mdv)"
[ ! -x "$viewer" ] && {
	viewer="$(command -v bat) -lmd"
	[ ! -x "$viewer" ] && {
		viewer="$(command -v cat)"
	}
}

case "$mode" in
	prs | issues | repos) gh search $mode "${args[@]}" | column -t -s $'\t' -H 2 | fzf --tabstop=4 --preview "fetch -r -d '$DIR' -c 'gh ${mode[1, -2]} view' {1} | GH_FORCE_TTY=1 $viewer" | awk '{print $1}' ;;
	*) gh search $mode "${args[@]}" | column -t -s $'\t' -H 2 | fzf --tabstop=4 | awk '{print $1}' ;;
esac
