#!/bin/env zsh

set -eo pipefail

local self="$(basename "$ZSH_ARGZERO")"

local default_dst=/usr/bin
local setDst=false
local sudo=sudo
# TERMUX__HOME=''
if [ -d "$TERMUX__HOME" ]; then
	sudo='' && default_dst="$TERMUX__PREFIX/bin"
fi
local dst="$default_dst"
local update=false
local verbose=false
local flag=-s

quietly() {
	$verbose || return
	for arg in "$@"; do
		echo "$arg" >&2
	done
}

helpText() {
	cat <<-EOF
		 usage: $self [FILE]...
		     a script installer for void-linux

		     -d, --directory set the directory items will be linked into (defaults to ${default_dst})
		     -f, --flags     set the flags used for symbolic linking
		     -u, --update    install all uninstalled scripts

		     if your file names have spaces, dis ting ain't fah yuh
	EOF
}

local arg
local args=()
for arg in "$@"; do
	[ setDst = true ] && {
		dst="$arg"
		setDst=false
		continue
	}
	case "$arg" in
		-f | --force) flag="-fs" ;;
		-d | --directory) setDst=true ;;
		-u | --update) update=true ;;
		-h | --help)
			helpText
			exit 0
			;;
		-*)
			echo "unrecognized flag: $arg" >&2
			exit 1
			;;
		*) args+=("$arg") ;;
	esac
done

local input="${args[@]}"
[ -n "$input" ] || {
	if [ -t 0 ]; then
		[ $update = true ] || {
			helpText
			exit 1
		}
		for name in "$DOTFILES"/scripts/*; do
			[ -x "$name" ] || continue
			input+=("$name")
		done
	else
		input="$(cat)"
		[ -n "$input" ] || {
			echo "no input provided" >&2
			helpText
			exit 1
		}
	fi
}

local name
local exit_code=0

while read -r name; do
	chmod +x "$name" || {
		echo "chmod failed with $?" >&2
		exit_code=1
		continue
	}

	echo "successfully set execute permission for '$name'" >&2

	local base="$(basename "$name")"
	[ $? = 0 ] || {
		echo "failed getting basename($name)" >&2
		exit_code=1
		continue
	}

	local new="$dst/$base"
	[ -e "$new" ] && {
		echo "$new already exists" >&2
		local real="$(realpath "$new")"
		[ "$real" = "$name" ] || {
			echo "realpath($new) == '$real'" >&2
			exit_code=1
			continue
		}
		echo "already linked('$name' -> '$new')"
		continue
	}

	$sudo ln $flag "$name" "$new" || {
		if [ -n "$sudo" ]; then
			echo "failed sudo(ln[$flag]('$name' -> '$dst'))" >&2
		else
			echo "failed ln[$flag]('$name' -> '$dst')" >&2
		fi
		exit_code=1
		continue
	}

	echo "successfully linked '$name' into '$dst'"

done < <(echo "$input" | sed 's/\s+/\n/g' | xargs realpath)

exit $exit_code
