#!/bin/env zsh

if [ -n "$(command -v xclip)" ]; then
	xclip -o -selection clipboard
elif [ -n "$(command -v termux-clipboard-get)" ]; then
	termux-clipboard-get
else
	echo no clipboard getter found
	exit 1
fi
exit $?
