#!/bin/env sh

# copy tmux's buffer to system clipboard

if [ $# = 0 ]; then
	[ -n "$TERMUX__PREFIX" ] && {
		tmux save-buffer - | termux-clipboard-set
		exit $?
	}
	tmux save-buffer - | xclip -i -selection clipboard
else
	[ -n "$TERMUX__PREFIX" ] && {
		tmux save-buffer "$@" | termux-clipboard-set
		exit $?
	}
	tmux save-buffer "$@" | xclip -i -selection clipboard
fi
exit $?
