#!/bin/env zsh

# figure out why a package was installed by xbps

set -euo pipefail

self="$(basename "$ZSH_ARGZERO")"
desc="$(realpath "$ZSH_ARGZERO" | xargs -d '\n' cat | head -3 | tail -1)"

manuals="$(xbps-query -m | sort -u)"
installed="$(xbps-query -l | grep '^ii' | awk '{print $2}' | sort -u)"

info() {
	printf '%s:' "$self" >&2
	printf ' %s' $@ >&2
	printf '\n' >&2
}

code=0
error() {
	code=1
	info "$@"
}

fatal() {
	error "$@"
	exit 1
}

case $# in
	0) fatal no args given ;;
	1)
		preface() { :; }
		pad() { echo "$1" | sed -E "s:-[0-9\-\._]+$::"; }
		;;
	*)
		preface() { echo "$arg:"; }
		pad() { printf '\t%s\n' "$1" | sed -E "s:-[0-9\-\._]+$::"; }
		;;
esac

for arg in "$@"; do
	[ -z "$(printf '%s' "$manuals" | egrep "^$arg-[0-9\._\-]+")" ] || {
		preface "$arg"
		printf "\tinstalled yourself\n"
		continue
	}
	[ -z "$(printf '%s' "$installed" | egrep "^$arg-[0-9\._\-]+")" ] || {
		preface "$arg"
		comm -12 <(printf '%s' "$manuals") <(xbps-query -X "$arg") | while read -r pkg; do
			pad "$pkg"
		done
		continue
	}
	info no package named "'$arg'" was ever installed by xbps
	command -v "$arg" &>/dev/null || {
		error no executable named "'$arg'" was found
		continue
	}
	read -rA matches <<<"$(comm -12 <(xlocate "$arg" | egrep "/$arg\s*$" | awk '{print $1}' | sort -u | egrep -v '^\s*$') <(printf '%s' "$installed"))"
	((${#matches})) || continue
	pkgs=()
	for match in "${matches[@]}"; do
		[ -n "$match" ] || continue
		! grep -q "$match" <<<"$manuals" || {
			pkgs+=("$match")
			continue
		}
		comm -12 <(printf '%s' "$manuals") <(xbps-query -X "$match") | egrep -v '^\s*$' | while read -r pkg; do
			[ -z "$pkg" ] || pkgs+=("$pkg")
		done
	done
	((${#pkgs})) || continue
	preface "$arg"
	printf '%s\n' $pkgs | sort -u | while read -r pkg; do
		pad "$pkg"
	done
done

exit $code
