#!/bin/env sh

self="$(basename "$0")"

error() {
	printf '%s:' "$self" >&2
	# shellcheck disable=SC2068
	printf ' %s' $@ >&2
	printf '\n' >&2
}

fatal() {
	error "$@"
	exit 1
}

if [ -x "$(command -v sk)" ]; then
	finder=sk
elif [ -x "$(command -v fzf)" ]; then
	finder=fzf
else
	echo "neither fzf or sk are installed" >&2
	exit 1
fi

tmp="$(mktemp)" || fatal "couldn't source bindings"
grep '^export' "$DOTFILES/.zshenv" | grep -E 'FZF|SKIM' >"$tmp"
. "$tmp"
rm "$tmp"

# shellcheck disable=SC2046
choices="$(xbps-install -nSu | cut -f1 -d' ' | sed 's/-[^-]*$//g' | $finder | tr '\n' ' ')"

[ -n "$choices" ] || exit

guard=pkexec
command -v "$guard" >/dev/null 2>/dev/null || guard=sudo

# shellcheck disable=SC2086
while ! $guard xbps-install -Syu $choices; do :; done
